import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 360)
x = np.radians(x)
y = np.sin(x)
plt.xlim(0,7)
plt.ylim(-1,1)
plt.title("Función Seno")
plt.ylabel("sin(x)")
plt.xlabel("Ángulo(rad)")
plt.plot(x,y, "m--")
plt.show()
print("-----------------------------------------------------------------------------------------------------")
x = np.arange(0, 360)
x = np.radians(x)
y = np.sin(x)
plt.xlim(0,7)
plt.ylim(-1,1)
plt.title("Función Seno")
plt.xlabel("Ángulo(rad)")
plt.plot(x,y, "m--", label =  "Función Seno")
plt.plot(x,np.cos(x), "g", label = "Función Coseno")
plt.legend(loc = "upper right")
plt.show()