import numpy as np
import matplotlib.pyplot as plt
print("PRIMER PUNTO")
x = np.arange(0, 360)
x = np.radians(x)
y = np.sin(x)
plt.xlim(0,7)
plt.ylim(-1,1)
plt.title("Función Seno")
plt.ylabel("sin(x)")
plt.xlabel("Ángulo(rad)")
plt.plot(x,y, "m--")
plt.show()
print("-----------------------------------------------------------------------------------------------------")
x = np.arange(0, 360)
x = np.radians(x)
y = np.sin(x)
plt.xlim(0,7)
plt.ylim(-1,1)
plt.title("Función Seno")
plt.xlabel("Ángulo(rad)")
plt.plot(x,y, "m--", label =  "Función Seno")
plt.plot(x,np.cos(x), "g", label = "Función Coseno")
plt.legend(loc = "upper right")
plt.show()

print("-----------------------------------------------------------------------------------------------------")
print("SEGUNDO PUNTO: GENERAR UN HISTOGRAMA")
import seaborn as sns
datos = np.random.randn(50000) *2 + 20  
plt.title("Histograma")
plt.xlabel("Valor x")
plt.ylabel("Probabilidad")
plt.xlim(12,30)
plt.ylim(0,0.25)
# Graficar la línea de densidad que sigue el borde del histograma
sns.kdeplot(datos, color='m',linestyle="--", linewidth=1.5)
plt.hist(datos, bins=150, density=True, alpha=0.2, color="red",linewidth=0.1, rwidth=1,edgecolor="black")
plt.show()

print("-----------------------------------------------------------------------------------------------------")
print("TERCER PUNTO")
x = np.arange(-10,10)
plt.xlim(-6,6)
plt.xticks(np.arange(-10, 11, 1))
plt.ylim(-10,10)
plt.yticks(np.arange(-10, 11, 1))
plt.axhline(y=0, color='black', linewidth=0.8, linestyle='--')
plt.axvline(x=0, color='black', linewidth=0.8, linestyle='--')
plt.plot(x,2*x+1)
plt.grid()
plt.plot(x,-(x**2))